title: Simple keyword detection rule for ifconfig
id: 09166932-075a-4f3c-9941-6eb20a339edf
status: experimental
description:
- '''change mac address with ifconfig'''
- '''changing mac address with ifconfig'''
references:
- https://github.com/RoseSecurity/Red-Teaming-TTPs/blob/main/Linux.md
- N/A
author: '@mthcht'
date: 2023/07/30
modified: 2023/08/13
tags:
- attack.T1027
- attack.T1036.004
- attack.T1059.001
- attack.T1497.001
- attack.TA0002
- attack.TA0005
logsource:
  category:
  - endpoint
falsepositives:
- Unknown
level:
- medium
- Unknown
detection:
  selection:
    ParentCommandLine:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    CommandLine:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    Details:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    registry.value:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    process.args:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    process.command_line:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    process.env_vars:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    process.io.text:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    process.title:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    pe.company:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    pe.description:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    pe.product:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    os.full:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    host.hostname:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    event.original:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    email.subject:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    device.model.name:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    container.image.name:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
    container.name:
    - '*ifconfig * hw ether *:*:*'
    - '*ifconfig * hw ether *'
  condition: selection
fields:
- ParentCommandLine
- CommandLine
- Details
- registry.value
- process.args
- process.command_line
- process.env_vars
- process.io.text
- process.title
- pe.company
- pe.description
- pe.product
- os.full
- host.hostname
- event.original
- email.subject
- device.model.name
- container.image.name
- container.name
