title: Simple keyword detection rule for produkey
id: 38630b59-53af-4fcf-87dd-e1a55edccc5d
status: experimental
description:
- '''ProduKey is a small utility that displays the ProductID and the CD-Key of Microsoft
  Office (Microsoft Office 2003. Microsoft Office 2007). Windows (Including Windows
  8/7/Vista). Exchange Server. and SQL Server installed on your computer. You can
  view this information for your current running operating system. or for another
  operating system/computer - by using command-line options. This utility can be useful
  if you lost the product key of your Windows/Office. and you want to reinstall it
  on your computer.'''
references:
- https://www.nirsoft.net/utils/product_cd_key_viewer.html
author: '@mthcht'
date: 2023/07/30
modified: 2023/08/13
tags:
- attack.T1003.001
- attack.T1003.002
- attack.T1012
- attack.T1057
- attack.T1518
- attack.TA0006
- attack.TA0007
- attack.TA0009
logsource:
  category:
  - endpoint
  - network
falsepositives:
- Unknown
level:
- Unknown
detection:
  selection:
    Image:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    OriginalFileName:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    CurrentDirectory:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ParentImage:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ParentCommandLine:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    TargetFilename:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Signature:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    signature:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ImageLoaded:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Company:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Description:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    description:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    CommandLine:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    SourceImage:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    TargetImage:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    CallTrace:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    TargetObject:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Details:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    PipeName:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Consumer:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Destination:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Query:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    NewName:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    StartAddress:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    StartModule:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    StartFunction:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    SourceHostname:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Device:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    file_name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    file_path:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    process:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    original_file_name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    parent_process:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    process_path:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    service_path:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    registry_path:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    registry_value_data:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    registry_value_name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ContextInfo:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Payload:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ScriptBlockText:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ServerName:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    TransportName:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    NewProcessName:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ParentProcessName:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Application:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Product Name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Threat Name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Process Name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    Path:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ImagePath:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ServiceName:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ProcessPath:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    AppName:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    AppPath:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    ModulePath:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    registry.data.strings:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    registry.path:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    registry.value:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    process.args:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    process.command_line:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    process.env_vars:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    process.io.text:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    process.executable:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    process.name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    process.title:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    pe.company:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    pe.description:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    pe.original_file_name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    pe.product:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    os.full:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    host.hostname:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    file.fork_name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    file.name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    file.path:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    file.target_path:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    email.attachments.file.name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    email.subject:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    dll.path:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    device.model.name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    container.image.name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    container.name:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    object:
    - '*produkey.zip*'
    - '*\ProduKey.exe*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    url:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    dest_url:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    uri:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    uri_query:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    query:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    url_domain:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    uri_path:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    domain:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    QueryName:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    QueryResults:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    DestinationHostname:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    DestinationIp:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    http_referrer:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    http_referrer_domain:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    http_user_agent:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    dest_nt_host:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    sender:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    recipient:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    orig_recipient:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    subject:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    url.domain:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    url.full:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    url.original:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    url.query:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    user_agent.original:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    network.application:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    http.request.body.content:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    http.request.referrer:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    email.from.address:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    dns.question.name:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
    destination.domain:
    - '*produkey.zip*'
    - '*produkey-x64.zip*'
    - '*/ProduKey.exe*'
    - '*produkey_setup.exe*'
  condition: selection
fields:
- Image
- OriginalFileName
- CurrentDirectory
- ParentImage
- ParentCommandLine
- TargetFilename
- Signature
- signature
- ImageLoaded
- Company
- Description
- description
- CommandLine
- SourceImage
- TargetImage
- CallTrace
- TargetObject
- Details
- PipeName
- Consumer
- Destination
- Name
- Query
- NewName
- StartAddress
- StartModule
- StartFunction
- SourceHostname
- Device
- file_name
- file_path
- process
- original_file_name
- parent_process
- process_path
- service_path
- registry_path
- registry_value_data
- registry_value_name
- ContextInfo
- Payload
- ScriptBlockText
- ServerName
- TransportName
- NewProcessName
- ParentProcessName
- Application
- Product Name
- Threat Name
- Process Name
- Path
- ImagePath
- ServiceName
- ProcessPath
- AppName
- AppPath
- ModulePath
- registry.data.strings
- registry.path
- registry.value
- process.args
- process.command_line
- process.env_vars
- process.io.text
- process.executable
- process.name
- process.title
- pe.company
- pe.description
- pe.original_file_name
- pe.product
- os.full
- host.hostname
- file.fork_name
- file.name
- file.path
- file.target_path
- email.attachments.file.name
- email.subject
- dll.path
- device.model.name
- container.image.name
- container.name
- object
- url
- dest_url
- uri
- uri_query
- query
- url_domain
- uri_path
- domain
- QueryName
- QueryResults
- DestinationHostname
- DestinationIp
- http_referrer
- http_referrer_domain
- http_user_agent
- dest_nt_host
- sender
- recipient
- orig_recipient
- subject
- url.domain
- url.full
- url.original
- url.query
- user_agent.original
- network.application
- http.request.body.content
- http.request.referrer
- email.from.address
- dns.question.name
- destination.domain
